#/*
#**  Sherlock - Copyright 1992, 1993, 1994
#**    Harfmann Software
#**    Compuserve: 73147,213
#**    All rights reserved
#*/

all: catch.exe

.SUFFIXES:
.SUFFIXES: .obj .c

catch.exe:  catch.c
	icc -W3 -Ti -Fm catch.c
