BASE=process
CFLAGS=/Q+ /Ss /W3 /Gm- /Gd- /Ti /O+ /C
LFLAGS=/NOI /MAP /NOL /A:16 /EXEPACK /BASE:65536 /DE

.SUFFIXES: .c

.c.obj:
    icc $(CFLAGS) $*.c

$(BASE).exe: $*.obj $*.def
    link386 $(LFLAGS) $*,,, os2386,$*;

process.obj: process.c procstat.h
